import React from "react";
import {
  Document,
  Page,
  Text,
  Image,
  StyleSheet,
  View,
} from "@react-pdf/renderer";
import { ItineraryData } from "../types/itenary";

const DEFAULT_LOGO =
  "https://td-production-images.s3.ap-south-1.amazonaws.com/Company/logo_f40ac362-0dc1-426c-a3f0-eaa66a18f184.png?X-Amz-Expires=604800&response-content-type=image%2Fpng&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAR3BJ4BUYEYXQ5HPZ%2F20250308%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Date=20250308T124426Z&X-Amz-SignedHeaders=host&X-Amz-Signature=f507e690dd11e18e5fe2e33ecb06792a3cb95060d382b45c0092d2be7b7a739e"; // Default company logo URL

const styles = StyleSheet.create({
  page: { padding: 30 },
  header: { textAlign: "center", fontSize: 18, fontWeight: "bold" },
  section: { marginBottom: 20 },
  title: { fontSize: 14, fontWeight: "bold" },
  paragraph: { fontSize: 12 },
  image: { width: "100%", height: "auto" },
  footer: { textAlign: "center", marginTop: 20 },
});

const ItineraryPDF: React.FC<{ itinerary: ItineraryData }> = ({
  itinerary,
}) => {
  return (
    <Document>
      <Page style={styles.page}>
        <View style={styles.header}>
          <Text>{itinerary.companyInfo.companyName}</Text>
          <Image
            src={itinerary.companyImages.companyLogo || DEFAULT_LOGO}
            style={{ width: 100, height: 100 }}
          />
        </View>

        <View style={styles.section}>
          <Text style={styles.title}>Traveller Details</Text>
          <Text>Name: {itinerary.travellerDetails.guestName}</Text>
          <Text>Arrival: {itinerary.travellerDetails.arrivalDate}</Text>
          <Text>Contact: {itinerary.travellerDetails.contactNumber}</Text>
          <Text>
            Arrival Location: {itinerary.travellerDetails.arrivalLocation}
          </Text>
          <Text>
            Departure Location: {itinerary.travellerDetails.departureLocation}
          </Text>
          <Text>Adults: {itinerary.travellerDetails.adults}</Text>
          <Text>Children: {itinerary.travellerDetails.children}</Text>
          <Text>
            Child Age: {itinerary.travellerDetails.childAge.join(", ")}
          </Text>
          <Text>Meal Plan: {itinerary.travellerDetails.mealPlan}</Text>
          <Text>
            Package Nights: {itinerary.travellerDetails.packageNights}
          </Text>
          <Text>
            Vehicle(s): {itinerary.travellerDetails.vehicle.join(", ")}
          </Text>
          <Text>
            Special Requests: {itinerary.travellerDetails.specialRequests}
          </Text>
        </View>

        {itinerary.itineraryDetails.map((day) => (
          <View key={day.dayNumber} style={styles.section}>
            <Text style={styles.title}>Day {day.dayNumber}</Text>
            <Text>Stay Location: {day.nightStayLocation}</Text>
            <Text>Hotel: {day.hotelName}</Text>

            {day.destinations.map((destination, index) => (
              <View key={index} style={styles.section}>
                <Text style={styles.title}>{destination.destinationName}</Text>
                <Text>{destination.destinationDescription}</Text>
                {destination.destinationImages && (
                  <Image
                    style={styles.image}
                    src={destination.destinationImages}
                  />
                )}
                <Text>Attractions: {destination.attractions.join(", ")}</Text>
              </View>
            ))}
          </View>
        ))}

        <View style={styles.footer}>
          <Text>Generated by {itinerary.companyInfo.companyName}</Text>
          {itinerary.companyImages.companyLastPageImage && (
            <Image
              src={itinerary.companyImages.companyLastPageImage}
              style={styles.image}
            />
          )}
        </View>
      </Page>
    </Document>
  );
};

export default ItineraryPDF;
